// Code generated by SQLBoiler 4.13.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	AgentVersions        string
	IPAddresses          string
	Keys                 string
	MultiAddresses       string
	PeerLogs             string
	Peers                string
	PeersXMultiAddresses string
	Protocols            string
	ProtocolsSets        string
	Requests             string
	RequestsDenormalized string
}{
	AgentVersions:        "agent_versions",
	IPAddresses:          "ip_addresses",
	Keys:                 "keys",
	MultiAddresses:       "multi_addresses",
	PeerLogs:             "peer_logs",
	Peers:                "peers",
	PeersXMultiAddresses: "peers_x_multi_addresses",
	Protocols:            "protocols",
	ProtocolsSets:        "protocols_sets",
	Requests:             "requests",
	RequestsDenormalized: "requests_denormalized",
}
