// Code generated by MockGen. DO NOT EDIT.
// Source: proto/nebula/v1/nebula_grpc.pb.go
//
// Generated by this command:
//
//	mockgen -package nebulav1 -source proto/nebula/v1/nebula_grpc.pb.go -destination proto/nebula/v1/nebula_grpc.mock.go
//

// Package nebulav1 is a generated GoMock package.
package nebulav1

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
	grpc "google.golang.org/grpc"
)

// MockNebulaServiceClient is a mock of NebulaServiceClient interface.
type MockNebulaServiceClient struct {
	ctrl     *gomock.Controller
	recorder *MockNebulaServiceClientMockRecorder
	isgomock struct{}
}

// MockNebulaServiceClientMockRecorder is the mock recorder for MockNebulaServiceClient.
type MockNebulaServiceClientMockRecorder struct {
	mock *MockNebulaServiceClient
}

// NewMockNebulaServiceClient creates a new mock instance.
func NewMockNebulaServiceClient(ctrl *gomock.Controller) *MockNebulaServiceClient {
	mock := &MockNebulaServiceClient{ctrl: ctrl}
	mock.recorder = &MockNebulaServiceClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNebulaServiceClient) EXPECT() *MockNebulaServiceClientMockRecorder {
	return m.recorder
}

// GetLatestPeerIDs mocks base method.
func (m *MockNebulaServiceClient) GetLatestPeerIDs(ctx context.Context, in *GetLatestPeerIDsRequest, opts ...grpc.CallOption) (*GetLatestPeerIDsResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetLatestPeerIDs", varargs...)
	ret0, _ := ret[0].(*GetLatestPeerIDsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLatestPeerIDs indicates an expected call of GetLatestPeerIDs.
func (mr *MockNebulaServiceClientMockRecorder) GetLatestPeerIDs(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLatestPeerIDs", reflect.TypeOf((*MockNebulaServiceClient)(nil).GetLatestPeerIDs), varargs...)
}

// GetPeer mocks base method.
func (m *MockNebulaServiceClient) GetPeer(ctx context.Context, in *GetPeerRequest, opts ...grpc.CallOption) (*GetPeerResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetPeer", varargs...)
	ret0, _ := ret[0].(*GetPeerResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPeer indicates an expected call of GetPeer.
func (mr *MockNebulaServiceClientMockRecorder) GetPeer(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPeer", reflect.TypeOf((*MockNebulaServiceClient)(nil).GetPeer), varargs...)
}

// GetRegisteredNetworks mocks base method.
func (m *MockNebulaServiceClient) GetRegisteredNetworks(ctx context.Context, in *GetRegisteredNetworksRequest, opts ...grpc.CallOption) (*GetRegisteredNetworksResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetRegisteredNetworks", varargs...)
	ret0, _ := ret[0].(*GetRegisteredNetworksResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRegisteredNetworks indicates an expected call of GetRegisteredNetworks.
func (mr *MockNebulaServiceClientMockRecorder) GetRegisteredNetworks(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRegisteredNetworks", reflect.TypeOf((*MockNebulaServiceClient)(nil).GetRegisteredNetworks), varargs...)
}

// GetRegisteredProjects mocks base method.
func (m *MockNebulaServiceClient) GetRegisteredProjects(ctx context.Context, in *GetRegisteredProjectsRequest, opts ...grpc.CallOption) (*GetRegisteredProjectsResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetRegisteredProjects", varargs...)
	ret0, _ := ret[0].(*GetRegisteredProjectsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRegisteredProjects indicates an expected call of GetRegisteredProjects.
func (mr *MockNebulaServiceClientMockRecorder) GetRegisteredProjects(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRegisteredProjects", reflect.TypeOf((*MockNebulaServiceClient)(nil).GetRegisteredProjects), varargs...)
}

// MockNebulaServiceServer is a mock of NebulaServiceServer interface.
type MockNebulaServiceServer struct {
	ctrl     *gomock.Controller
	recorder *MockNebulaServiceServerMockRecorder
	isgomock struct{}
}

// MockNebulaServiceServerMockRecorder is the mock recorder for MockNebulaServiceServer.
type MockNebulaServiceServerMockRecorder struct {
	mock *MockNebulaServiceServer
}

// NewMockNebulaServiceServer creates a new mock instance.
func NewMockNebulaServiceServer(ctrl *gomock.Controller) *MockNebulaServiceServer {
	mock := &MockNebulaServiceServer{ctrl: ctrl}
	mock.recorder = &MockNebulaServiceServerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNebulaServiceServer) EXPECT() *MockNebulaServiceServerMockRecorder {
	return m.recorder
}

// GetLatestPeerIDs mocks base method.
func (m *MockNebulaServiceServer) GetLatestPeerIDs(arg0 context.Context, arg1 *GetLatestPeerIDsRequest) (*GetLatestPeerIDsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLatestPeerIDs", arg0, arg1)
	ret0, _ := ret[0].(*GetLatestPeerIDsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLatestPeerIDs indicates an expected call of GetLatestPeerIDs.
func (mr *MockNebulaServiceServerMockRecorder) GetLatestPeerIDs(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLatestPeerIDs", reflect.TypeOf((*MockNebulaServiceServer)(nil).GetLatestPeerIDs), arg0, arg1)
}

// GetPeer mocks base method.
func (m *MockNebulaServiceServer) GetPeer(arg0 context.Context, arg1 *GetPeerRequest) (*GetPeerResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPeer", arg0, arg1)
	ret0, _ := ret[0].(*GetPeerResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPeer indicates an expected call of GetPeer.
func (mr *MockNebulaServiceServerMockRecorder) GetPeer(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPeer", reflect.TypeOf((*MockNebulaServiceServer)(nil).GetPeer), arg0, arg1)
}

// GetRegisteredNetworks mocks base method.
func (m *MockNebulaServiceServer) GetRegisteredNetworks(arg0 context.Context, arg1 *GetRegisteredNetworksRequest) (*GetRegisteredNetworksResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRegisteredNetworks", arg0, arg1)
	ret0, _ := ret[0].(*GetRegisteredNetworksResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRegisteredNetworks indicates an expected call of GetRegisteredNetworks.
func (mr *MockNebulaServiceServerMockRecorder) GetRegisteredNetworks(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRegisteredNetworks", reflect.TypeOf((*MockNebulaServiceServer)(nil).GetRegisteredNetworks), arg0, arg1)
}

// GetRegisteredProjects mocks base method.
func (m *MockNebulaServiceServer) GetRegisteredProjects(arg0 context.Context, arg1 *GetRegisteredProjectsRequest) (*GetRegisteredProjectsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRegisteredProjects", arg0, arg1)
	ret0, _ := ret[0].(*GetRegisteredProjectsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRegisteredProjects indicates an expected call of GetRegisteredProjects.
func (mr *MockNebulaServiceServerMockRecorder) GetRegisteredProjects(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRegisteredProjects", reflect.TypeOf((*MockNebulaServiceServer)(nil).GetRegisteredProjects), arg0, arg1)
}

// mustEmbedUnimplementedNebulaServiceServer mocks base method.
func (m *MockNebulaServiceServer) mustEmbedUnimplementedNebulaServiceServer() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "mustEmbedUnimplementedNebulaServiceServer")
}

// mustEmbedUnimplementedNebulaServiceServer indicates an expected call of mustEmbedUnimplementedNebulaServiceServer.
func (mr *MockNebulaServiceServerMockRecorder) mustEmbedUnimplementedNebulaServiceServer() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "mustEmbedUnimplementedNebulaServiceServer", reflect.TypeOf((*MockNebulaServiceServer)(nil).mustEmbedUnimplementedNebulaServiceServer))
}

// MockUnsafeNebulaServiceServer is a mock of UnsafeNebulaServiceServer interface.
type MockUnsafeNebulaServiceServer struct {
	ctrl     *gomock.Controller
	recorder *MockUnsafeNebulaServiceServerMockRecorder
	isgomock struct{}
}

// MockUnsafeNebulaServiceServerMockRecorder is the mock recorder for MockUnsafeNebulaServiceServer.
type MockUnsafeNebulaServiceServerMockRecorder struct {
	mock *MockUnsafeNebulaServiceServer
}

// NewMockUnsafeNebulaServiceServer creates a new mock instance.
func NewMockUnsafeNebulaServiceServer(ctrl *gomock.Controller) *MockUnsafeNebulaServiceServer {
	mock := &MockUnsafeNebulaServiceServer{ctrl: ctrl}
	mock.recorder = &MockUnsafeNebulaServiceServerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUnsafeNebulaServiceServer) EXPECT() *MockUnsafeNebulaServiceServerMockRecorder {
	return m.recorder
}

// mustEmbedUnimplementedNebulaServiceServer mocks base method.
func (m *MockUnsafeNebulaServiceServer) mustEmbedUnimplementedNebulaServiceServer() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "mustEmbedUnimplementedNebulaServiceServer")
}

// mustEmbedUnimplementedNebulaServiceServer indicates an expected call of mustEmbedUnimplementedNebulaServiceServer.
func (mr *MockUnsafeNebulaServiceServerMockRecorder) mustEmbedUnimplementedNebulaServiceServer() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "mustEmbedUnimplementedNebulaServiceServer", reflect.TypeOf((*MockUnsafeNebulaServiceServer)(nil).mustEmbedUnimplementedNebulaServiceServer))
}
