// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: nebula/v1/nebula.proto

package nebulav1

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	NebulaService_GetRegisteredProjects_FullMethodName = "/nebula.v1.NebulaService/GetRegisteredProjects"
	NebulaService_GetRegisteredNetworks_FullMethodName = "/nebula.v1.NebulaService/GetRegisteredNetworks"
	NebulaService_GetPeer_FullMethodName               = "/nebula.v1.NebulaService/GetPeer"
	NebulaService_GetLatestPeerIDs_FullMethodName      = "/nebula.v1.NebulaService/GetLatestPeerIDs"
)

// NebulaServiceClient is the client API for NebulaService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NebulaServiceClient interface {
	GetRegisteredProjects(ctx context.Context, in *GetRegisteredProjectsRequest, opts ...grpc.CallOption) (*GetRegisteredProjectsResponse, error)
	GetRegisteredNetworks(ctx context.Context, in *GetRegisteredNetworksRequest, opts ...grpc.CallOption) (*GetRegisteredNetworksResponse, error)
	GetPeer(ctx context.Context, in *GetPeerRequest, opts ...grpc.CallOption) (*GetPeerResponse, error)
	GetLatestPeerIDs(ctx context.Context, in *GetLatestPeerIDsRequest, opts ...grpc.CallOption) (*GetLatestPeerIDsResponse, error)
}

type nebulaServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewNebulaServiceClient(cc grpc.ClientConnInterface) NebulaServiceClient {
	return &nebulaServiceClient{cc}
}

func (c *nebulaServiceClient) GetRegisteredProjects(ctx context.Context, in *GetRegisteredProjectsRequest, opts ...grpc.CallOption) (*GetRegisteredProjectsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRegisteredProjectsResponse)
	err := c.cc.Invoke(ctx, NebulaService_GetRegisteredProjects_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nebulaServiceClient) GetRegisteredNetworks(ctx context.Context, in *GetRegisteredNetworksRequest, opts ...grpc.CallOption) (*GetRegisteredNetworksResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRegisteredNetworksResponse)
	err := c.cc.Invoke(ctx, NebulaService_GetRegisteredNetworks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nebulaServiceClient) GetPeer(ctx context.Context, in *GetPeerRequest, opts ...grpc.CallOption) (*GetPeerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPeerResponse)
	err := c.cc.Invoke(ctx, NebulaService_GetPeer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nebulaServiceClient) GetLatestPeerIDs(ctx context.Context, in *GetLatestPeerIDsRequest, opts ...grpc.CallOption) (*GetLatestPeerIDsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetLatestPeerIDsResponse)
	err := c.cc.Invoke(ctx, NebulaService_GetLatestPeerIDs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NebulaServiceServer is the server API for NebulaService service.
// All implementations must embed UnimplementedNebulaServiceServer
// for forward compatibility.
type NebulaServiceServer interface {
	GetRegisteredProjects(context.Context, *GetRegisteredProjectsRequest) (*GetRegisteredProjectsResponse, error)
	GetRegisteredNetworks(context.Context, *GetRegisteredNetworksRequest) (*GetRegisteredNetworksResponse, error)
	GetPeer(context.Context, *GetPeerRequest) (*GetPeerResponse, error)
	GetLatestPeerIDs(context.Context, *GetLatestPeerIDsRequest) (*GetLatestPeerIDsResponse, error)
	mustEmbedUnimplementedNebulaServiceServer()
}

// UnimplementedNebulaServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedNebulaServiceServer struct{}

func (UnimplementedNebulaServiceServer) GetRegisteredProjects(context.Context, *GetRegisteredProjectsRequest) (*GetRegisteredProjectsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRegisteredProjects not implemented")
}

func (UnimplementedNebulaServiceServer) GetRegisteredNetworks(context.Context, *GetRegisteredNetworksRequest) (*GetRegisteredNetworksResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRegisteredNetworks not implemented")
}

func (UnimplementedNebulaServiceServer) GetPeer(context.Context, *GetPeerRequest) (*GetPeerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPeer not implemented")
}

func (UnimplementedNebulaServiceServer) GetLatestPeerIDs(context.Context, *GetLatestPeerIDsRequest) (*GetLatestPeerIDsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLatestPeerIDs not implemented")
}
func (UnimplementedNebulaServiceServer) mustEmbedUnimplementedNebulaServiceServer() {}
func (UnimplementedNebulaServiceServer) testEmbeddedByValue()                       {}

// UnsafeNebulaServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NebulaServiceServer will
// result in compilation errors.
type UnsafeNebulaServiceServer interface {
	mustEmbedUnimplementedNebulaServiceServer()
}

func RegisterNebulaServiceServer(s grpc.ServiceRegistrar, srv NebulaServiceServer) {
	// If the following call pancis, it indicates UnimplementedNebulaServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&NebulaService_ServiceDesc, srv)
}

func _NebulaService_GetRegisteredProjects_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRegisteredProjectsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NebulaServiceServer).GetRegisteredProjects(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NebulaService_GetRegisteredProjects_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NebulaServiceServer).GetRegisteredProjects(ctx, req.(*GetRegisteredProjectsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NebulaService_GetRegisteredNetworks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRegisteredNetworksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NebulaServiceServer).GetRegisteredNetworks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NebulaService_GetRegisteredNetworks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NebulaServiceServer).GetRegisteredNetworks(ctx, req.(*GetRegisteredNetworksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NebulaService_GetPeer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPeerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NebulaServiceServer).GetPeer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NebulaService_GetPeer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NebulaServiceServer).GetPeer(ctx, req.(*GetPeerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NebulaService_GetLatestPeerIDs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLatestPeerIDsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NebulaServiceServer).GetLatestPeerIDs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NebulaService_GetLatestPeerIDs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NebulaServiceServer).GetLatestPeerIDs(ctx, req.(*GetLatestPeerIDsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// NebulaService_ServiceDesc is the grpc.ServiceDesc for NebulaService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NebulaService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "nebula.v1.NebulaService",
	HandlerType: (*NebulaServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetRegisteredProjects",
			Handler:    _NebulaService_GetRegisteredProjects_Handler,
		},
		{
			MethodName: "GetRegisteredNetworks",
			Handler:    _NebulaService_GetRegisteredNetworks_Handler,
		},
		{
			MethodName: "GetPeer",
			Handler:    _NebulaService_GetPeer_Handler,
		},
		{
			MethodName: "GetLatestPeerIDs",
			Handler:    _NebulaService_GetLatestPeerIDs_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "nebula/v1/nebula.proto",
}
