name: Test, Build & Push (dev)

on:
  workflow_call:
    outputs:
      imageTag:
        description: "The image tag that was pushed to ECR"
        value: ${{ jobs.push_to_ecr.outputs.imageTag }}

# TODO: move to workflow inputs:
env:
  AWS_REGION: us-east-1
  AWS_ROLE: arn:aws:iam::019120760881:role/prod-use1-github-oidc-role
  AWS_ECR_REPOSITORY: probelab

jobs:
  push_to_ecr:
    name: Build & Push
    runs-on: ubuntu-latest
    outputs:
      imageTag: ${{ steps.meta.outputs.image }}
    steps:
      - name: Checking out the Repository
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Configuring AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: ${{ env.AWS_ROLE }}
          role-session-name: PushToECR

      - name: Logging in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Building ants Image Metadata
        id: meta
        run: |
          SHA_SHORT=${{ github.sha }}
          SHA_SHORT=${SHA_SHORT::7}
          
          NAMESPACE=${{ steps.login-ecr.outputs.registry }}
          TAG="ants-sha${SHA_SHORT}"
          
          IMAGE="$NAMESPACE/$AWS_ECR_REPOSITORY:$TAG"
          
          echo "tag=$TAG" >> $GITHUB_OUTPUT
          echo "image=$IMAGE" >> $GITHUB_OUTPUT

      - name: Checking if Image exists in ECR
        id: check-ecr
        run: |
          aws ecr describe-images --repository-name $AWS_ECR_REPOSITORY --image-ids imageTag=${{ steps.meta.outputs.tag }} || exit_code=$?
          echo "exit_code=$exit_code" >> $GITHUB_OUTPUT

      - name: Building Docker Image ${{ steps.meta.outputs.tag }}
        id: build
        if: steps.check-ecr.outputs.exit_code != 0
        run: docker build -t ${{ steps.meta.outputs.image }} .

      - name: Pushing Docker Image ${{ steps.meta.outputs.tag }} to Amazon ECR
        id: push
        if: steps.check-ecr.outputs.exit_code != 0
        run: docker push ${{ steps.meta.outputs.image }}
