name: Deployment

on:
  workflow_dispatch:
    inputs:
      ref:
        description: "Which ref should be checked out?"

jobs:
  test:
    name: Test & Lint
    uses: ./.github/workflows/workflow_call_test_lint.yml
    with:
      ref: ${{ inputs.ref }}
    permissions:
      id-token: write
      contents: read

  build_push:
    name: Deployment
    uses: ./.github/workflows/workflow_call_build_push.yml
    needs: test
    with:
      ref: ${{ inputs.ref }}
    permissions:
      id-token: write
      contents: read

  deploy:
    name: Deployment
    uses: ./.github/workflows/workflow_call_deploy.yml
    needs: build_push
    permissions:
      id-token: write
      contents: read
    with:
      ref: ${{ inputs.ref }}
      imageTag: ${{ needs.build_push.outputs.imageTag }}
    secrets:
      slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
