name: Pull Request

on:
  pull_request:
    branches:
      - dev
      - main

jobs:
  test:
    name: Ants
    uses: ./.github/workflows/test.yml
    permissions:
      id-token: write
      contents: read