name: Push (prod)

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  test:
    name: Deployment
    uses: ./.github/workflows/test.yml
    permissions:
      id-token: write
      contents: read

  build_push:
    name: Deployment
    uses: ./.github/workflows/build_push.yml
    needs: test
    permissions:
      id-token: write
      contents: read

  deploy:
    name: Deployment
    uses: ./.github/workflows/deploy.yml
    needs: build_push
    permissions:
      id-token: write
      contents: read
    with:
      imageTag: ${{ needs.build_push.outputs.imageTag }}
    secrets:
      slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
